#include <stdio.h>
#include <stdlib.h>
#include "ft_printf.h"

int		main(void)
{
	int		r1;
	int		r2;

	setbuf(stdout, NULL);

	printf("-------------------------------------\n");
	r1 = printf("42%- 58.60hhD42\n", 0);
	r2 = ft_printf("42%- 58.60hhD42\n", 0);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%060.6hhD\n", 0);
	r2 = ft_printf("%060.6hhD\n", 0);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%%\n");
	r2 = ft_printf("%%\n");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%#-08x\n", 42);
	r2 = ft_printf("%#-08x\n", 42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%hU\n", 4294967296);
	r2 = ft_printf("%hU\n", 4294967296);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%");
	r2 = ft_printf("%");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% ");
	r2 = ft_printf("% ");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% h\n");
	r2 = ft_printf("% h\n");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%Z\n");
	r2 = ft_printf("%Z\n");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% hZ\n");
	r2 = ft_printf("% hZ\n");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% hZ%\n");
	r2 = ft_printf("% hZ%\n");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% Z\n", "test");
	r2 = ft_printf("% Z\n", "test");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% Z \n", "test");
	r2 = ft_printf("% Z \n", "test");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%%%", "test");
	r2 = ft_printf("%%%", "test");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%%   %", "test");
	r2 = ft_printf("%%   %", "test");
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%ll#x\n", 9223372036854775807);
	r2 = ft_printf("%ll#x\n", 9223372036854775807);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("% Z\n", 42);
	r2 = ft_printf("% Z\n", 42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%5+d\n", 42);
	r2 = ft_printf("%5+d\n", 42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%5+d\n", -42);
	r2 = ft_printf("%5+d\n", -42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%-5+d\n", 42);
	r2 = ft_printf("%-5+d\n", 42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%-5+d\n", -42);
	r2 = ft_printf("%-5+d\n", -42);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%lhl\n", 9223372036854775807);
	r2 = ft_printf("%lhl\n", 9223372036854775807);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%lhh\n", 2147483647);
	r2 = ft_printf("%lhh\n", 2147483647);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%hhld\n", 128);
	r2 = ft_printf("%hhld\n", 128);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("@main_ftprintf: %####0000 33..1..#00d\\n", 256);
	r2 = ft_printf("@main_ftprintf: %####0000 33..1..#00d\\n", 256);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("@main_ftprintf: %####0000 33..1d\n", 256);
	r2 = ft_printf("@main_ftprintf: %####0000 33..1d\n", 256);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("@main_ftprintf: %###-#0000 33...12..#0+0d\n", 256);
	r2 = ft_printf("@main_ftprintf: %###-#0000 33...12..#0+0d\n", 256);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("[>------------<%60.48hhD>------------<]\n", 0);
	r2 = ft_printf("[>------------<%60.48hhD>------------<]\n", 0);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%llld\n", 1);
	r2 = ft_printf("%llld\n", 1);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");
	r1 = printf("%12.48hhi\n", 0);
	r2 = ft_printf("%12.48hhi\n", 0);
	printf("%d, %d\n", r1, r2);
	printf("-------------------------------------\n");

	return (0);
}
